mqtt:
  broker:
    host: ssl://stream.dev.dimo.zone
    port: 8884
    tls:
      enabled: true
  topics:
    status: devices/%s/status
    network: devices/%s/network
    logs: devices/%s/logs
    fingerprint: devices/%s/fingerprint
  client:
    buffering:
      fileStore: /opt/autopi/store
      cleanSession: false
      connectRetryInterval: 10
      limit: 200
services:
  auth:
    host: https://auth.dev.dimo.zone
    clientId: step-ca
    clientSecret: KsQ7pruHob6D3NLFQEg9
    caFingerprint: a563363f0bc9cc76031695743c059cf1e694f294e4d1548e981d18cb96348f5f
    generateChallengeURI: /auth/web3/generate_challenge
    submitChallengeURI: /auth/web3/submit_challenge
  ca:
    host: https://ca.dev.dimo.zone
    certPath: /opt/autopi/client.crt
    privateKeyPath: /opt/autopi/client.pem
  identity:
    host: https://identity-api.dev.dimo.zone/query
  vehicle:
    host: https://vehicle-signal-decoding.dev.dimo.zone