mqtt:
  broker:
    host: ssl://stream.dimo.zone
    port: 8883
    tls:
      enabled: true
  topics:
    status: devices/%s/status
    network: devices/%s/network
    logs: devices/%s/logs
    fingerprint: devices/%s/fingerprint
  client:
    buffering:
      fileStore: /opt/autopi/store
      cleanSession: false
      connectRetryInterval: 10
      limit: 200
services:
  auth:
    host: https://auth.dimo.zone
    clientId: step-ca
    clientSecret: mkoLsNAfiG2DM2DfqYsX
    caFingerprint: 9992e3ce6a87c5d8dc6a09daddd4365c9e0f50593f3e897dedc1b89c037270ed
    generateChallengeURI: /auth/web3/generate_challenge
    submitChallengeURI: /auth/web3/submit_challenge
  ca:
    host: https://ca.dimo.zone
    certPath: /opt/autopi/client.crt
    privateKeyPath: /opt/autopi/client.pem
  identity:
    host: https://identity-api.dimo.zone/query
  vehicle:
    host: https://vehicle-signal-decoding.dimo.zone