// Code generated by MockGen. DO NOT EDIT.
// Source: template_store.go
//
// Generated by this command:
//
//	mockgen -source template_store.go -destination mocks/template_store_mock.go
//
// Package mock_loggers is a generated GoMock package.
package mock_loggers

import (
	reflect "reflect"

	models "github.com/DIMO-Network/edge-network/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplateStore is a mock of TemplateStore interface.
type MockTemplateStore struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateStoreMockRecorder
}

// MockTemplateStoreMockRecorder is the mock recorder for MockTemplateStore.
type MockTemplateStoreMockRecorder struct {
	mock *MockTemplateStore
}

// NewMockTemplateStore creates a new mock instance.
func NewMockTemplateStore(ctrl *gomock.Controller) *MockTemplateStore {
	mock := &MockTemplateStore{ctrl: ctrl}
	mock.recorder = &MockTemplateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateStore) EXPECT() *MockTemplateStoreMockRecorder {
	return m.recorder
}

// DeleteAllSettings mocks base method.
func (m *MockTemplateStore) DeleteAllSettings() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllSettings")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllSettings indicates an expected call of DeleteAllSettings.
func (mr *MockTemplateStoreMockRecorder) DeleteAllSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllSettings", reflect.TypeOf((*MockTemplateStore)(nil).DeleteAllSettings))
}

// ReadDBCFile mocks base method.
func (m *MockTemplateStore) ReadDBCFile() (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDBCFile")
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDBCFile indicates an expected call of ReadDBCFile.
func (mr *MockTemplateStoreMockRecorder) ReadDBCFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDBCFile", reflect.TypeOf((*MockTemplateStore)(nil).ReadDBCFile))
}

// ReadPIDsConfig mocks base method.
func (m *MockTemplateStore) ReadPIDsConfig() (*models.TemplatePIDs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPIDsConfig")
	ret0, _ := ret[0].(*models.TemplatePIDs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPIDsConfig indicates an expected call of ReadPIDsConfig.
func (mr *MockTemplateStoreMockRecorder) ReadPIDsConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPIDsConfig", reflect.TypeOf((*MockTemplateStore)(nil).ReadPIDsConfig))
}

// ReadTemplateDeviceSettings mocks base method.
func (m *MockTemplateStore) ReadTemplateDeviceSettings() (*models.TemplateDeviceSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadTemplateDeviceSettings")
	ret0, _ := ret[0].(*models.TemplateDeviceSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadTemplateDeviceSettings indicates an expected call of ReadTemplateDeviceSettings.
func (mr *MockTemplateStoreMockRecorder) ReadTemplateDeviceSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadTemplateDeviceSettings", reflect.TypeOf((*MockTemplateStore)(nil).ReadTemplateDeviceSettings))
}

// ReadTemplateURLs mocks base method.
func (m *MockTemplateStore) ReadTemplateURLs() (*models.TemplateURLs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadTemplateURLs")
	ret0, _ := ret[0].(*models.TemplateURLs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadTemplateURLs indicates an expected call of ReadTemplateURLs.
func (mr *MockTemplateStoreMockRecorder) ReadTemplateURLs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadTemplateURLs", reflect.TypeOf((*MockTemplateStore)(nil).ReadTemplateURLs))
}

// ReadVINConfig mocks base method.
func (m *MockTemplateStore) ReadVINConfig() (*models.VINLoggerSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadVINConfig")
	ret0, _ := ret[0].(*models.VINLoggerSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadVINConfig indicates an expected call of ReadVINConfig.
func (mr *MockTemplateStoreMockRecorder) ReadVINConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadVINConfig", reflect.TypeOf((*MockTemplateStore)(nil).ReadVINConfig))
}

// ReadVehicleInfo mocks base method.
func (m *MockTemplateStore) ReadVehicleInfo() (*models.VehicleInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadVehicleInfo")
	ret0, _ := ret[0].(*models.VehicleInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadVehicleInfo indicates an expected call of ReadVehicleInfo.
func (mr *MockTemplateStoreMockRecorder) ReadVehicleInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadVehicleInfo", reflect.TypeOf((*MockTemplateStore)(nil).ReadVehicleInfo))
}

// WriteDBCFile mocks base method.
func (m *MockTemplateStore) WriteDBCFile(dbcFile *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteDBCFile", dbcFile)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteDBCFile indicates an expected call of WriteDBCFile.
func (mr *MockTemplateStoreMockRecorder) WriteDBCFile(dbcFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteDBCFile", reflect.TypeOf((*MockTemplateStore)(nil).WriteDBCFile), dbcFile)
}

// WritePIDsConfig mocks base method.
func (m *MockTemplateStore) WritePIDsConfig(settings models.TemplatePIDs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePIDsConfig", settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// WritePIDsConfig indicates an expected call of WritePIDsConfig.
func (mr *MockTemplateStoreMockRecorder) WritePIDsConfig(settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePIDsConfig", reflect.TypeOf((*MockTemplateStore)(nil).WritePIDsConfig), settings)
}

// WriteTemplateDeviceSettings mocks base method.
func (m *MockTemplateStore) WriteTemplateDeviceSettings(settings models.TemplateDeviceSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteTemplateDeviceSettings", settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteTemplateDeviceSettings indicates an expected call of WriteTemplateDeviceSettings.
func (mr *MockTemplateStoreMockRecorder) WriteTemplateDeviceSettings(settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteTemplateDeviceSettings", reflect.TypeOf((*MockTemplateStore)(nil).WriteTemplateDeviceSettings), settings)
}

// WriteTemplateURLs mocks base method.
func (m *MockTemplateStore) WriteTemplateURLs(settings models.TemplateURLs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteTemplateURLs", settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteTemplateURLs indicates an expected call of WriteTemplateURLs.
func (mr *MockTemplateStoreMockRecorder) WriteTemplateURLs(settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteTemplateURLs", reflect.TypeOf((*MockTemplateStore)(nil).WriteTemplateURLs), settings)
}

// WriteVINConfig mocks base method.
func (m *MockTemplateStore) WriteVINConfig(settings models.VINLoggerSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteVINConfig", settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteVINConfig indicates an expected call of WriteVINConfig.
func (mr *MockTemplateStoreMockRecorder) WriteVINConfig(settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteVINConfig", reflect.TypeOf((*MockTemplateStore)(nil).WriteVINConfig), settings)
}

// WriteVehicleInfo mocks base method.
func (m *MockTemplateStore) WriteVehicleInfo(settings models.VehicleInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteVehicleInfo", settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteVehicleInfo indicates an expected call of WriteVehicleInfo.
func (mr *MockTemplateStoreMockRecorder) WriteVehicleInfo(settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteVehicleInfo", reflect.TypeOf((*MockTemplateStore)(nil).WriteVehicleInfo), settings)
}
